# This file contains per-environment settings for AnyCable.
#
# Since AnyCable config is based on anyway_config (https://github.com/palkan/anyway_config), all AnyCable settings
# can be set or overridden through the corresponding environment variables.
# E.g., `rpc_host` is overridden by ANYCABLE_RPC_HOST, `debug` by ANYCABLE_DEBUG etc.
#
# Note that AnyCable recognizes REDIS_URL env variable for Redis pub/sub adapter. If you want to
# use another Redis instance for AnyCable, provide ANYCABLE_REDIS_URL variable.
#
# Read more about AnyCable configuration here: https://docs.anycable.io/ruby/configuration
#
default: &default
  # Turn on/off access logs ("Started..." and "Finished...")
  access_logs_disabled: false
  rpc_host: "127.0.0.1:50051"
  log_grpc: false
  broadcast_adapter: redis
  redis_channel: "__anycable__"
  redis_url: <%= ENV.fetch('ANYCABLE_REDIS_URL', 'redis://redis:6379/0') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
